name: Kompresor

on:
  - workflow_dispatch
  - push

jobs:
  starter:
    name: kompredd
    runs-on: ubuntu-latest
    steps:
      - name: gaskan
        run: |
          echo "::group::Deps"
          sudo apt update -qq -y && DEBIAN_FRONTEND=noninteractive sudo apt install -qq -y aria2 ffmpeg wget curl
          echo "::endgroup::"
          echo "::group::Dw"
          aria2c https://transfer.sh/11D4JVH/rizal.mp4
          echo "::endgroup::"
          echo "::group::Kompres"
          ffmpeg -i *mp4 -c:v libx264 -preset medium -tune film -crf 26 -vf scale=-2:480 -c:a copy rizal-Comp.mp4
          echo "::endgroup::"
          du -sh rizal-Comp.mp4
          curl -F "file=@rizal-Comp.mp4" https://api.bayfiles.com/upload
