name: Kompresor

on:
  workflow_dispatch:
    inputs:
      LINK:
        description: 'Link supported by aria2'
        required: true

jobs:
  starter:
    name: kompredd
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: gaskan
        run: sudo bash kom.sh ${{ github.event.inputs.LINK }}